# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RooballBallSkillsTracker' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Work around Xcode 26.4+ Apple Clang rejecting fmt 11.0.2 consteval checks.
    fmt_base_header = File.join(installer.sandbox.pod_dir('fmt'), 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_header)
      fmt_base = File.read(fmt_base_header)
      patched_fmt_base = fmt_base.gsub(
        /^#\s*define FMT_USE_CONSTEVAL 1$/,
        '#  define FMT_USE_CONSTEVAL 0'
      )

      if patched_fmt_base != fmt_base
        File.chmod(0644, fmt_base_header)
        File.write(fmt_base_header, patched_fmt_base)
      end
    end
  end
end
